"""add note timestemp

Revision ID: 44258d38e2f8
Revises: a0bd5fbd5365
Create Date: 2019-03-14 17:42:33.848720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44258d38e2f8'
down_revision = 'a0bd5fbd5365'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note') as branch_op:
        branch_op.add_column(sa.Column('timestemp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note') as branch_op:
        branch_op.drop_column('timestemp')
    # ### end Alembic commands ###
